### ISSUE TITLE
JWT Authorization in Swagger UI

### ISSUE THREAD

**Issue by jkulcsar** [leonardocartaxo/ts-node-boilerplate#2]
Great work with this boilerplate!
I've noticed the following in the Swagger UI: adding the `'Bearer <space> <JWT-token-here>'`  will not add the Authorization header to subsequent calls. I've copied the JWT out of the response after the admin user authenticated with login.
In the `tsoa.json` file I've tried to upgrade it to OpenAPi 3 by adding `"specVersion": 3` to `"swagger"` however still no luck. Perhaps I'm forgetting something.
Thanks for your help!

**Comment by leonardocartaxo** [comment]
Thanks for the feedback.

I noticed this bug, but I can't figure out how to solve it. When I have some time I will try solved again. In mean while if you figure out how to solve it, please send me a merge request.
